import React from 'react';
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
} from "../../components/ui/sheet";
import { ScrollArea } from "../../components/ui/scroll-area";
import { Card, CardContent } from "../../components/ui/card";
import { Shield, Lock, Users, Database, Cloud } from "lucide-react";

const PolicySection = ({ icon: Icon, title, children }) => (
  <Card className="mb-6">
    <CardContent className="pt-6">
      <div className="flex items-start gap-4">
        <div className="mt-1">
          <Icon className="h-6 w-6 text-blue-600" />
        </div>
        <div>
          <h2 className="text-xl font-semibold mb-3">{title}</h2>
          {children}
        </div>
      </div>
    </CardContent>
  </Card>
);

const PoliciesSheet = ({ open, onOpenChange }) => {
  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="right" className="w-full sm:max-w-full">
        <SheetHeader>
          <SheetTitle className="text-2xl font-bold">EdBotz Data Privacy & Security Policies</SheetTitle>
          <SheetDescription>
            Our commitment to protecting student privacy and securing educational data
          </SheetDescription>
        </SheetHeader>
        
        <ScrollArea className="h-[calc(100vh-8rem)] mt-6 pr-4">
          <div className="space-y-6">
            <PolicySection icon={Shield} title="Data Privacy Overview">
              <div className="space-y-3 text-gray-600">
                <p>
                  EdBotz is designed with student privacy as a core principle. Our platform facilitates AI-enhanced learning while ensuring that no student personal information is collected or stored.
                </p>
                <p>
                  We understand the importance of data privacy in educational settings and have implemented strict measures to protect both teacher and student information.
                </p>
              </div>
            </PolicySection>

            <PolicySection icon={Users} title="Student Data Protection">
              <div className="space-y-3 text-gray-600">
                <p className="font-medium text-blue-600">
                  No Student Personal Information is Stored
                </p>
                <p>
                  • Students do not need to create accounts or provide any personal information
                </p>
                <p>
                  • Chat interactions with AI assistants are not permanently stored
                </p>
                <p>
                  • Access is provided through secure links generated by teachers
                </p>
                <p className="mt-4">
                  We strongly advise teachers not to include any student-specific information when creating or configuring AI assistants.
                </p>
              </div>
            </PolicySection>

            <PolicySection icon={Lock} title="Teacher Account Security">
              <div className="space-y-3 text-gray-600">
                <p>
                  Teacher accounts are secured through:
                </p>
                <p>
                  • Authentication via Google or Microsoft authentication services
                </p>
                <p>
                  • Minimal data collection - only storing authentication-related information
                </p>
                <p>
                  • Secure session management and automatic timeouts
                </p>
              </div>
            </PolicySection>

            <PolicySection icon={Database} title="Data Storage & Encryption">
              <div className="space-y-3 text-gray-600">
                <p>
                  All data in EdBotz is protected using industry-standard security measures:
                </p>
                <p>
                  • Data is encrypted both in transit and at rest using Firebase Realtime Database security
                </p>
                <p>
                  • Teacher-created content is stored with encryption
                </p>
             
              </div>
            </PolicySection>

            <PolicySection icon={Cloud} title="AI Processing & Data Governance">
              <div className="space-y-3 text-gray-600">
                <p className="font-medium">
                  Google Cloud Vertex AI Compliance:
                </p>
                <p>
                  • No customer data is used to train foundation models
                </p>
                <p>
                  • Chat inputs and outputs are only cached for up to 24 hours to improve performance
                </p>
                <p>
                  • Project-level privacy is enforced for all cached data
                </p>
                <p>
                  • Schools can opt out of caching if required (may affect performance)
                </p>
                <p className="mt-4">
                  EdBotz follows Google Cloud's AI/ML Privacy Commitment and adheres to their robust data governance practices. All processing is compliant with Google's Cloud Data Processing Addendum (CDPA).
                </p>
              </div>
            </PolicySection>

            <div className="mt-8 p-4 bg-blue-50 rounded-lg">
              <p className="text-sm text-gray-600">
                For additional information about our data privacy practices or to request specific details about our security measures, please contact us. We are committed to maintaining transparency and addressing any concerns from educational institutions.
              </p>
            </div>
          </div>
        </ScrollArea>
      </SheetContent>
    </Sheet>
  );
};

export default PoliciesSheet;